// src/features/countdown-button/ui/CountdownButton.vue
<script setup lang="ts">
import { CustomButton } from "@/shared/ui";
import { computed, watch } from "vue";
import { useCountdown } from "@/shared/hooks";

interface Props {
  delayInMs: number;
  isEnabled: boolean;
  onClick: () => void;
}

const props = defineProps<Props>();
const isEnabled = computed(() => props.isEnabled);
const delayInSec = computed(() => props.delayInMs / 1000);
const { timeLeft, start, stop, reset } = useCountdown(delayInSec);

watch(isEnabled, () => {
  if (isEnabled.value) {
    return start();
  }

  stop();
});

// Functions
function onClickFx() {
  props.onClick();
  reset();
  start();
}
// Functions END
</script>

<template>
  <custom-button
    variant="link"
    color="secondary"
    :disabled="timeLeft > 0"
    class="countdown_button"
    @click="onClickFx"
  >
    <slot :time="timeLeft" />
  </custom-button>
</template>

<style scoped>
.countdown_button:disabled {
  text-decoration: none !important;
  color: #97a1af !important;
}
</style>

// src/features/countdown-button/ui/CountdownButton.tsx
import { useCountdownButton } from "../hooks/useCountdownButton";
import classes from "./styles.module.css";
import { Button } from "@/shared/ui";

interface Props {
  className?: string;
  delayInMs: number;
  isEnabled: boolean;
  onClick: () => void;
}

export function CountdownButton({
  className = "",
  delayInMs,
  isEnabled,
  onClick
}: Props) {
  const { value, onClickFx } = useCountdownButton({ delayInMs, isEnabled, onClick });
  const classNames = `${classes["countdown_button"]} ${value > 0 && classes["countdown_button_disabled"]} ${className}`;

  return (
    <Button variant="link" color="secondary" className={classNames} onClick={onClickFx}>
      {value <= 0 ? "Отправить ещё раз" : `Отправить код повторно через ${value} сек`}
    </Button>
  );
}
