// src/pages/login/ui/LoginPage.vue
<script setup lang="ts">
import {
  CustomButton,
  CustomContainer,
  CustomInput,
  CustomTypography
} from "@/shared/ui";
import { onlyNumbersRegex } from "@/shared/config";
import { useLoginPage } from "@/pages/login/hooks";
import { CountdownButton } from "@/features/countdown-button";

const { form, isOtpShowed, isLoading, otpCountdown, sendOtpAgain, onSubmit } =
  useLoginPage();

const [phoneModel, phoneProps] = form.defineField("phone");
const [otpCodeModel, otpCodeProps] = form.defineField("otpCode");
</script>

<template>
  <custom-container class="default-page-vertical-offsets">
    <form class="login_page_wrapper" @submit="onSubmit">
      <custom-typography variant="title">Авторизация</custom-typography>
      <custom-typography variant="regular">
        Введите номер телефона для входа в личный кабинет
      </custom-typography>

      <custom-input
        v-model="phoneModel"
        v-bind="phoneProps"
        placeholder="Телефон"
        :error-message="form.errors.value.phone"
        :pattern-on-input="onlyNumbersRegex"
      />

      <custom-input
        v-show="isOtpShowed"
        v-model="otpCodeModel"
        v-bind="otpCodeProps"
        placeholder="Код"
        :error-message="form.errors.value.otpCode"
        :pattern-on-input="onlyNumbersRegex"
      />

      <custom-button
        variant="contained"
        color="primary"
        class="login_page_button"
        type="submit"
        :disabled="isLoading"
      >
        {{ !isOtpShowed ? "Продолжить" : "Войти" }}
      </custom-button>

      <countdown-button
        v-show="isOtpShowed"
        v-slot="{ time }"
        :on-click="sendOtpAgain"
        class="login_page_countdown_button"
        :delay-in-ms="otpCountdown"
        :is-enabled="isOtpShowed"
      >
        {{ time <= 0 ? "Отправить ещё раз" : `Отправить код повторно через ${time} сек` }}
      </countdown-button>
    </form>
  </custom-container>
</template>

<style scoped>
.login_page_wrapper {
  display: flex;
  flex-direction: column;
  gap: 24px;
  max-width: 464px;
}

.login_page_button {
  max-width: 328px;
}

.login_page_countdown_button {
  align-self: baseline;
  width: fit-content;
}
</style>

// src/pages/login/ui/LoginPage.tsx
import { OTP_VALUE_LENGTH } from "../config";
import { useLoginPage } from "../hooks";
import classes from "./styles.module.css";
import { Button, Container, Input, Typography } from "@/shared/ui";
import { CountdownButton } from "@/features/countdown-button";
import { onlyNumbersRegex } from "@/shared/config";

export function LoginPage() {
  const {
    otpCountdown,
    isLoading,
    isOtpShowed,
    formErrors,
    register,
    onFormSubmit,
    sendOtpAgain
  } = useLoginPage();

  return (
    <Container className="default-page-vertical-offsets">
      <form className={classes["login_page_wrapper"]} onSubmit={onFormSubmit}>
        <Typography variant="title" tag="h1">
          Вход
        </Typography>
        <Typography variant="regular" tag="p">
          Введите номер телефона для входа в личный кабинет
        </Typography>
        <Input
          className={classes["login_page_input"]}
          type="number"
          errorMessage={formErrors["phone"]?.message}
          disabled={isLoading || isOtpShowed}
          placeholder="Телефон"
          patternOnInput={onlyNumbersRegex}
          {...register("phone", {
            valueAsNumber: true,
            required: true
          })}
        />

        {isOtpShowed && (
          <Input
            className={classes["login_page_input"]}
            type="number"
            errorMessage={formErrors["otpCode"]?.message}
            placeholder="Проверочный код"
            disabled={isLoading}
            minLength={OTP_VALUE_LENGTH}
            maxLength={OTP_VALUE_LENGTH}
            patternOnInput={onlyNumbersRegex}
            required
            {...register("otpCode", {
              valueAsNumber: true
            })}
          />
        )}

        <Button
          variant="contained"
          color="primary"
          type="submit"
          disabled={isLoading}
          className={classes["login_page_submit_btn"]}
        >
          {!isOtpShowed ? "Продолжить" : "Войти"}
        </Button>

        <CountdownButton
          className={[
            classes["login_page_countdown_button"],
            !isOtpShowed ? classes["hidden"] : ""
          ].join(" ")}
          delayInMs={otpCountdown}
          isEnabled={isOtpShowed}
          onClick={sendOtpAgain}
        />
      </form>
    </Container>
  );
}
